export default {
  agamaOptions: [],
  hobiOptions: [],
  citacitaOptions: [],
  pendidikanOptions: [],
  pekerjaanOptions: [],
  penghasilanOptions: [],
  statusorangtuaOptions: [],
  statustempattinggalOptions: [],
  jarakrumahOptions: [],
  transportasiOptions: [],
  jabatanOptions: [],
  mengajarOptions: [],
  jenjangOptions: [],
  kelasOptions: [],
  kelasUseOptions: [],
  ProvinsiOptions: [],
  KabKotaOptions: [],
  KecamatanOptions: [],
  KelurahanOptions: [],
  KabKotaOnlyOptions: [],
  dataAdministrator: null,
  dataStruktural: null,
  dataSiswaSiswi: null,
  dataCMSSetting: null,
}